---
name: Test

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [[self-hosted, apexos-builder, linux, X64]]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install dependencies
        run: script/setup --dev

      - name: Run tests
        run: script/test_ci
